### ISSUE TITLE
Tables are not listing

### ISSUE THREAD

**Issue by justinjoseph89** [sleberknight/basic-hbase-examples#1]
Hi,
First am new to this Hbase concept. i was trying to list all the tables present my Hbase which is running on another virtual machine. I wrote this java client in my local machine ,
              HBaseAdmin admin = new HBaseAdmin(config);
             System.out.println( "getting HBaseAdmin");
             HTableDescriptor[] tables = admin.listTables();
             System.out.println( "tables");
             System.out.printf("Found %d table(s)\n", tables.length);
             for (HTableDescriptor table : tables) {
                 System.out.printf("%s\n", table.getNameAsString());
             }
But it is not producing any output. It stuck once it is printed till second line., after that it is not executing. Am using horton works sandbox. 
Is there any other things i should do if am running HBase and java client on different machines?

**Comment by sleberknight** [comment]
Did you first create any actual tables? There are some samples in the om.nearinfinity.explore.hbase.samples.basic package. You would first run CreateTable, then AddSomeData, then AddSomeMoreData, then GetRow.

Also look in the etc directory at the blog_sample_data.txt and blogpost_sample_data.txt files. You should be able to open an HBase shell and copy/paste the code from those files into the shell.

Also, this project is kind of old and is using HBase 0.96, which is now end-of-life and they recommend using 0.98. You could try updating the pom.xml to 0.98 and seeing if that changes anything once you are sure you have some tables.

**Comment by justinjoseph89** [comment]
Hi,
I created few tables in Hbase and added data into it. And i am able list those tables in the HBase shell also. And am using version 0.98. But still its not possible for me to list those tables using java as i done above.
Thanks.

**Comment by justinjoseph89** [comment]
Hi,
I created few tables in Hbase and added data into it. And i am able list those tables in the HBase shell also. And am using version 0.98. But still its not possible for me to list those tables using java as i done above.
Thanks.

**Comment by sleberknight** [comment]
I just updated the code to use 0.98.9 and use java 1.7. Try pulling down a standalone HBase distribution from hbase.apache.org and unpack it locally, then starting it via the start-hbase.sh script in the bin directory. Once you do that you should be able to use the various programs to create tables, load data, etc. For example, to load the fakenames sample data you can first run CreateFakenamesTable, and then run BulkLoadFakenamesData, which will use the sample data in the etc/fakenames-sample-1000.csv file. Once that's done you can run the various programs to get and scan data, e.g. GetSomeFakePeople or ScanFakePeople, which lets you select from a menu of choices for scanning. Of course this is a simple standalone server running locally, but it does work and lets you become familiar with the client API.

Not sure how the Hortonworks Sandbox HBase comes setup...is it running in distributed mode? Regardless I think you'd need to setup your local HBase configuration files to point to the remote HBase, e.g. by setting the configuration in hbase-site.xml and at the very least setting the hbase.master, hbase.zookeeper.quorum, and hbase.zookeeper.property.clientPort properties. But I haven't done this in quite a while so don't take my word for it, and so some Google searches for it.

**Comment by justinjoseph89** [comment]
Hi,
Thanks For the reply.It worked for me.
